### PR TITLE
Fixes for v0.5

### LINKED ISSUE #9: Tests fail on v0.5
The tests in the Arrays category fail with the following error trace for each failed fact:

```
ERROR: MethodError: no method matching length(::DBAPI.ArrayInterfaces.ColumnarArrayRowIterator) # Could be ColumnIterator too
Closest candidates are:
  length(::SimpleVector) at essentials.jl:168
  length(::Base.MethodList) at reflection.jl:256
  length(::MethodTable) at reflection.jl:322
  ...
 in _similar_for at ./array.jl:262 [inlined]
 in _collect at ./array.jl:277 [inlined]
 in collect(::DBAPI.ArrayInterfaces.ColumnarArrayRowIterator) at ./array.jl:273
```

This isn't in an issue on v0.4, and tests pass there. 

I checked the various methods defined for `length` and I found this one method that got defined in v0.4 but _not_ in v0.5

```
length(cursor::DBAPI.ArrayInterfaces.ColumnarArrayCursor) at /Users/ranjan/.julia/v0.4/DBAPI/src/arrays.jl:107
```

I wonder if this is causing the issue.

### PR DESCRIPTION
**Pull request by ranjanan**
This fixes tests on v0.5. Fixes #9

### CODE REVIEW

File: src/arrays.jl [hunk 1]
```diff
@@ -237,4 +238,11 @@ immutable ArrayInterfaceError{T<:AbstractString} <: DatabaseError{ColumnarArrayI
     message::T
 end
 
+if VERSION >= v"0.5-"
```
Comment (tkelman) [inline src/arrays.jl:241]: best to be more specific about VERSION dependent cutoffs like this, or use isdefined
